sul-dlss/sdr-deploy

README.md
deploy.rb

Speeds up cloning of repository.

adds depth parameter to git clone to speed up initial clone

---

deploy.rb

I found I needed these changes in order to 1. edit out the branch prompt in config/deploy.rb, and 2. to be able to pull down private repos without being asked for HTTPS credentials. It otherwise worked like a charm.
May I ask someone on @sul-dlss-labs/infrastructure-team who's successfully run sdr-deploy to try again w/ this branch?

Fix sed command and GitHub URL

---

README.md
deploy.rb
lib/auditor.rb

Prints this report at the end:
```
Errors found:
sul-dlss/common-accessioning: CVE-2020-8184
sul-dlss/dor-services-app: CVE-2020-8184
Summary:
NAME: rack
ADVISORY: CVE-2020-8184
CRITICALITY: Unknown
VERSION: 2.2.2
URL: https://groups.google.com/g/rubyonrails-security/c/OWtmozPH9Ak
TITLE: Percent-encoded cookies can be used to overwrite existing prefixed cookie names
SOLUTION: upgrade to ~> 2.1.4, >= 2.2.3
```

Add audit of gemfile

---

Gemfile
Gemfile.lock

first step in making this a deployable repo
- would you prefer one PR for all the setup, or a bunch of little ones?

add Gemfile

---

.github/pull_request_template.md

add github pr template to repo

---

README.md

To improve the documentation.
:eyes: 
README!

Update README to reflect bundler usage

---

README.md
deploy.rb

This dependency was declared and never used
n/a
README

Drop unused dependency

---

repos.yml

Remove lyberservices-scripts from deployments

---

repos.yml

Because sorting creates order, and order is good.
Ran the deploys.
repos.yml

Sort repos alphabetically

---

repos.yml

Add etd qa status URL

---

repos.yml

To reflect reality re: QA boxes.
By the next FR :laughing: 
repos.yml

Update repos now that we have full QA env built

---

README.md
repos.yml

- to avoid status check for hydrus qa that will always fail
- to make the README more accurate and easier to skim for info

Improvements

---

deploy.rb

noticed this usage explanation was missing when i went to do https://github.com/sul-dlss/DeveloperPlaybook/pull/156/
ran the command i put in the example
usage comment only

explain --check-cocina usage

---

deploy.rb

FIXES #52 
n/a
Added inline comment

Automatically run check cocina for deployments

---

repos.yml

Update H2 and Hydrus prod status checks.

---

lib/repo_updater.rb

* Improve progress bar by making clear what the current repo is 
* Render the progress bar immediately when updating repos, showing what repository is being created or updated currently. Prior to this change, if an error occurred while updating, e.g., google-books, the progress bar would still read gis-robot-suite, which was misleading.
* Also, reflect the current operation (updating or creating) inline in the progress bar instead of `puts`ing it out, which creates noise.
ran locally + CI
none

Make progressbar report current step more accurately

---

README.md

Update README to reflect work from #70

---

bin/deploy

Same small fix as yesterday in bin/check_cocina

Same typo as prior fix in another bin

---

config/settings.yml

new ksr rails app to deploy regularly

add ksr app to deploy scripts

---

README.md

Add a note about ruby 2.7 projects

---

README.md

Remove gis-robot-suite from the exception list

---

README.md
bin/tag
lib/repo_updater.rb
lib/tagger.rb

Fixes #76 
Also includes:
* Include CLI help output in README (Thor gives us pretty documentation... let's use it instead of rolling our own)

Add ability to create and delete git tags

---

README.md

Aiming for more correctness and less verbosity.

Spruce up documentation

---

README.md

Avoid Cocina model mismatches.

Added note about turning off GB.

---

README.md

Documentation of expectations is good.

Document our preferred release tag naming convention

---

Gemfile
Gemfile.lock
README.md
config/settings.yml
lib/deployer.rb
lib/sdr_deploy.rb

Fixes https://github.com/sul-dlss/argo/issues/3383
And, as part of this, flag it as needing confirmation before deployment to prod.

Reintroduce Argo to sdr-deploy CLI

---

lib/deployer.rb

Fixes #129 - suggestion during retro to require confirmation if you try to deploy main (i.e. without specifying a tag or specifying a tag of "main")

add a confirmation if you try to deploy without a tag

---

Gemfile.lock
README.md
bin/sdr
lib/tagger.rb

Tagging goodness for cocina-only deploys.
README

Allow tagging cocina only.

---

Gemfile
Gemfile.lock
README.md
config/settings.yml
lib/deployer.rb
lib/sdr_deploy.rb

~~This is ON HOLD while I test it with our first responder.~~
Fixes #128
This commit uses the `parallel` gem to run deploys in parallel.
Ran a few test deploys against QA. ~~Could use more testing.~~  Verified in all environments.

Parallelize deploys

---

README.md
config/settings.yml

Connects to sul-dlss/was-pywb#43
- Update README to remove outdated information
- Add was-pywb to list of deployable repositories
Deployed to QA, confirmed pywb was deployed

Add was-pywb to list of deployable repositories

---

README.md

I noticed a goof and a couple of improvements for the examples

readme gets a couple tweaks

---

README.md

To put the information where it is most likely to be noticed.

README: add note about io-wait and strscan to deploy instructions

---

README.md

there was an error in an example due to argument order.

README: fix and add to examples

---

config/settings.yml

Remove techmd retro.

---

config/settings.yml

This is now unblocked since supporting sul-embed work went to prod.

Do not skip H2 prod deploys any longer

---

.circleci/config.yml

Use latest ruby-rails orb in CI

---

README.md
config/settings.yml
lib/sdr_deploy.rb

And mark the uat env of sul_pub as a non-standard one.
N/A

Deploy non-standard envs along with prod

---

README.md

Updates that go along with https://github.com/sul-dlss/DeveloperPlaybook/pull/229

README updates to setup connect to sdr-infra.stanford.edu

---

README.md

Update README.md to clarify ssh config

---

README.md

Quick update that I should have included in my prior PR.

Add refresh_repos to readme

---

.rubocop.yml
README.md

Bump Ruby to 3.3.1

---

Gemfile
Gemfile.lock
config/settings.yml
lib/auditor.rb
lib/cocina_checker.rb
lib/deployer.rb
lib/sdr_deploy.rb

Quality of life: to make the UI arguably prettier and easier to grok, rather than a mess of newlines and indentation.
Ran many deploys

Make the UI less of a hot mess

---

config/settings.yml
lib/ssh_checker.rb

- **Add H3 to the list of deployable projects**
- **Parallelize SSH checking**
Ran the deployer and SSH checker.

Add H3 and parallelize SSH checks

---

.circleci/config.yml
.rubocop.yml
README.md

Keep pace with Ruby upgrades
CI

Bump to Ruby 3.4

---

config/settings.yml

Resolves https://github.com/sul-dlss/rialto-orgs/issues/81

Add rialto orgs

---

config/settings.yml

Fixes https://github.com/sul-dlss/heracles-etd/issues/204

Switch etds to heracles-etd
