sul-dlss/sdr-deploy

- repos.yml
We are decommissioning RIALTO, so no longer need to deploy updates.
> Remove rialto-etl from repos.yml

- deploy.rb
- repos.yml
- fix workflow-server-rails urls (d'oh)
- add a little separation and clarity to the reports printed at the end of a deploy
I waved my hands.
n/a
> fix workflow-service urls, add formatting

- README.md
- deploy.rb
- lib/auditor.rb
- I prefer COLOR output, when possible (yay) - Resolves #17
- fix oversight of mine on separator for reports that are deploy only.
- I just ran a deploy following the instructions for COLOR, and using the small change to deploy.rb
^^
> how to get color output, and formatting tweak

- lib/auditor.rb
Because script was complaining about missing gems for repos it wasn't even deploying.
I ran the script with the change.
n/a
> run bundle before bundle audit

- deploy.rb
figured it was something like this, but i was definitely nervous for a moment that i'd forgotten the `--checkssh` flag when i saw `Deploying tmp/repos/sul-dlss/dor_indexing_app` flash by on my terminal when i glanced back at it.
i included the `ssh_check` message because as it is, all you get is `Pseudo-terminal will not be allocated because stdin is not a terminal.` for each host.  a bit more inline info seemed like it'd be nice.
blood pressure reduction
ran `./deploy.rb stage --checkssh` from my laptop (haven't yet gotten to deploying, need to investigate some failing dependency updates to allow merging to happen)
n/a
> more accurate messaging for --checkssh usage

- deploy.rb
* at the start of the run, list repo names for which deployment or ssh_check is to happen
* log line and ### delimiter before and after each deploy, for easier visual skimming and text searching to find specific deployment output
* include both cap deploy result and status check result in final output, with a bit more nuance on the status check output
easier to determine deployment results at a glance, and whether issues are due to cap deployment or status URL check.
i ran both `--checkssh` mode and a regular deployment against both qa and stage.
none, changes should hopefully just clarify output
> output touchups

- README.md
It's only required in the projects that are being deployed (e.g. argo, hydrus, preassembly, etc)
```ruby
LOAD_PATH.unshift File.expand_path('lib', __dir__)
require 'auditor'
=> true
auditor = Auditor.new
auditor.audit(repo: 'argo', dir: 'tmp/repos/sul-dlss/argo')
=> nil
auditor.report
=> nil
```
Readme
> Bundler audit is not required by this project

- repos.yml
per comment from @jcoyne on a related ops tasks ticket
to fix the status URLs we hit for the workflow-server-rails app
`curl` from the preservation VMs, since those can reach the workflow-server-rails app (at present, we can't reach it from laptops, even on VPN, per the ops ticket that spawned this).
this is a config only update
> correct workflow-server-rails status URLs

- repos.yml
- We should hit the /status/all check for better and complete health check confirmation
- Remove health checks that cannot be hit due the servers being locked down from requests from the outside world (even when on full VPN)
Updating developer playbook to indicate how to manually do health checks for suri and workflow-service.  See https://github.com/sul-dlss/DeveloperPlaybook/pull/133
> Update status checks

- repos.yml
- small tweak to the (currently unused) health check URL for the non-standard sul_pub qa environment to make it match the actual VM name
- adjust the sul_pub stage health check to not do an "all" check, because harvesting of publication is turned off in stage on purpose and this will cause one of the health checks to fail there
- workflow-server-rails stage and qa now appear to be locked down, making us unable to do a health check across any environments from our laptops
> update status checks for sul-pub and workflow-server-rails

- repos.yml
Got this error at the tail end of the deploys, I think this will fix it by not having a nil `status` block when we do not have any URLs to check:
```
Traceback (most recent call last):
4: from ./deploy.rb:96:in `<main>'
3: from ./deploy.rb:96:in `each'
2: from ./deploy.rb:101:in `block in <main>'
1: from ./deploy.rb:101:in `chdir'
./deploy.rb:112:in `block (2 levels) in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
```
> comment out all status checks for workflow-server-rails to avoid error

- repos.yml
server has been decommissioned, can no longer connect or deploy to it.
see https://github.com/sul-dlss/was-thumbnail-service/issues/211
ran with the `--checkssh` flag against stage, currently running weekly dep updates against stage
n/a
> was-thumbnail-service has been decommissioned

- repos.yml
Fixes sul-dlss/happy-heron#10
Currently blocked by https://github.com/sul-dlss/happy-heron/issues/11 but should be ready soon. Will undraft once that's merged.
To add H2 to the list of deployed projects.
It will be tested by future FRs.
`repos.yml`
> Add happy-heron (h2) to deploy repos

- deploy.rb
- repos.yml
Some projects use 'main' instead of 'master'.  This allows us to configure those repos to use that branch, defaulting to master if not set.
> allow primary branch name to be configurable per repo

- deploy.rb
- repos.yml
Instead of hard-coding `master` or requiring novel configuration, ask git what the default branch is and deploy it. This is the approach we are using successfully in access-update-scripts. Also, use fetch and hard reset instead of checkout and pull, for further alignment with access-update-scripts.
I deployed to QA (for H2 and hydra_etd) and it worked.
None
> Simplify default branch logic

- repos.yml
preservation_catalog-01 fails a status check by design, but the check works on preservation-catalog-02, let's hit that instead
> use pres-cat-2 for checks since one check always fails on -1 by design

- README.md
- deploy.rb
This prevents you from deploying incompatible releases:
```
13:27 $ ./deploy.rb qa --check-cocina
repos to deploy: sul-dlss/argo, sul-dlss/common-accessioning, sul-dlss/dor-services-app, sul-dlss/dor_indexing_app, sul-dlss/gis-robot-suite, sul-dlss/google-books, sul-dlss/happy-heron, sul-dlss/hydra_etd, sul-dlss/hydrus, sul-dlss/modsulator-app-rails, sul-dlss/pre-assembly, sul-dlss/preservation_catalog, sul-dlss/preservation_robots, sul-dlss/robot-console, sul-dlss/sdr-api, sul-dlss/sul_pub, sul-dlss/suri-rails, sul-dlss/technical-metadata-service, sul-dlss/was-registrar-app, sul-dlss/was_robot_suite, sul-dlss/workflow-server-rails
------- COCINA REPORT -------
Found these versions of cocina in use:
cocina-models (0.43.0)
cocina-models (0.55.0)
cocina-models (0.56.0)
cocina-models …
```
> Create a report of which versions of cocina-models are the the lockfiles

- deploy.rb
* more tolerant parsing of CLI args
* more accurate display of current mode in output
* guard against accidentally running in deploy mode when user provides arg for unrecognized mode
locally:
```
sdr-deploy % ./deploy.rb stage --sshcheck # previously only 'checkssh' worked, and this would just launch deployment
repos to sshcheck: sul-dlss/argo, sul-dlss/common-accessioning, sul-dlss/dor-services-app, sul-dlss/dor_indexing_app, sul-dlss/gis-robot-suite, sul-dlss/google-books, sul-dlss/happy-heron, sul-dlss/hydra_etd, sul-dlss/hydrus, sul-dlss/modsulator-app-rails, sul-dlss/pre-assembly, sul-dlss/preservation_catalog, sul-dlss/preservation_robots, sul-dlss/robot-console, sul-dlss/sdr-api, sul-dlss/sul_pub, sul-dlss/suri-rails, sul-dlss/technical-metadata-service, sul-dlss/was-registrar-app, …
```
> touchups for slightly friendlier CLI operation

- repos.yml
explain expected okcomputer oddity
by browser
exclusively edited config comment
> comment clarification

- repos.yml
To get a successful status from the script instead of a failure due to 301
> update status url for h2 prod

- deploy.rb
implement suggestion on #53
bonus: use a consistent non-zero exit code when the script exits early
running locally, i:
* edited the `deploy` function on line 64 so that it would `check_ssh` instead of `deploy`ing (so i could test without really deploying).  then i ran ` ./deploy.rb qa`.
* kept the above `check_ssh` edit, then edited the new `cocina_check` method to always return `false` so that i could test the abort behavior.  then i ran ` ./deploy.rb qa`.
n/a
> check cocina-models version consistency after repos are updated

- repos.yml
to get more checks used for sdr-api (and make it like all the other repos)
> sdr-api status urls: use status/all

- Gemfile.lock
- README.md
To help the next person who hits the problem I hit.  :-P
> README:  include information about contribsys gem credentials for google-books

- lib/sdr_deploy.rb
Prior to this commit, and after we added bundler to sdr-deploy, executing `bundle install` for the google-books project could not successfully install sidekiq-pro due to needing the `BUNDLE_GEMS__CONTRIBSYS__COM` environment variable which `Bundler.with_unbundled_env` strips out.
CI + local run
None
> Inject contribsys credentials back into project bundler context

- bin/check_ssh
This step is slow and if you need to re-run this command after fixing the known_hosts file, it becomes a pain
> Add a way to skip the repo update when checking ssh

- README.md
- bin/check_cocina
- bin/check_ssh
- bin/deploy
- config/settings.yml
- lib/deployer.rb
- lib/repo_updater.rb
- lib/ssh_checker.rb
To make it easier to operate on a subset of repositories. Now requires no temporary config hacks.
Includes:
* Add new, mutually exclusive `--only` and `--except` options to `bin/deploy` and `bin/check_ssh`
* Add support for `-s` flag to `bin/deploy` (previously only available to `bin/check_ssh`)
* Fix outdated staging URL for technical metadata service causing status report to fail
* Update README to document new options
Ran all commands against all envs with different options. 🤷🏻 
README
> Add ability to operate on a subset of repositories

- bin/check_ssh
This fixes an error message I'm getting:
```
Traceback (most recent call last):
6: from bin/check_ssh:60:in `<main>'
5: from /Users/amcollie/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
4: from /Users/amcollie/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
3: from /Users/amcollie/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
2: from /Users/amcollie/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
1: from bin/check_ssh:40:in `check_ssh'
bin/check_ssh:55:in `repositories': uninitialized constant CheckSsh::Setting (NameError)
Did you mean?  Settings
String
```
> Fix typo Setting -> Settings

- config/settings.yml
> Remove Hydrus

- Gemfile.lock
- lib/cocina_checker.rb
This can happen if you use: --only sul-dlss/suri-rails
> Permit deploying when there are no cocina versions

- bin/deploy
- config/settings.yml
Do not automatically deploy Argo during the Fedora 3 workcycle, and show warning when deploying.
> do not deploy argo automatically during workcycle

- README.md
- lib/repo_updater.rb
Alternative to #96, just remove local repos that are not configured when updating, to prevent confusion when checking cocina versions.
Localhost
> remove unused local repos when updating

- config/settings.yml
ksr status checks are being added in https://github.com/sul-dlss/ksr-app/pull/12 .... we can then check them after that is merged
> add new ksr status check endpoints to deployment script

- README.md
FWIW I was able to deploy dor-services-app successfully when running sdr-deploy in ruby 3 on my laptop
> ksr-app now uses ruby 3

- config/settings.yml
Status check for techmd-prod is going to a non-responding URL.  i updated to the current deploy target, which works... see https://github.com/sul-dlss/technical-metadata-service/blob/main/config/deploy/prod.rb
> update url for techmd-prod status check

- bin/check_ssh
- bin/deploy
- lib/repo_updater.rb
Do not prune when operating on a subset of repositories, else repos are mistakenly pruned.
> Fix pruning bug

- config/settings.yml
Because this is the box that mounts the zip transfers dir and it avoids a failing status check. @jmartin-sul said so.
> Prefer prescat 02 VMs for status checks

- bin/deploy
Because I forgot about argo and DSA with the warning message as it was.  Apparently I can be bothered to actually read a few sentences.
> update warning message for dor-services-app and argo deploys

- .rubocop.yml
- README.md
- bin/deploy
- lib/deployer.rb
Fixes #77
This is a logical follow-up to the earlier commit that added the ability to tag a bunch of repos. It lets us deploy a specified tag instead of always deploying the latest in `main`. See #77 for more.
As part of this work, add a new check to the deployer that prevents a tag-based deploy if not all implicated repos have the tag already created.
Ran a bunch of tests in QA.
README
> Add ability to deploy a given tag for every repository

- lib/deployer.rb
previously, if i tried to deploy with a tag, i'd get an error like:
```
% bin/sdr deploy -t rel-2022-04-04 -e stage --except sul-dlss/dor-services-app        main
updating cached git repository [▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣] (19/19, ETA:  0s) sul-dlss/workflow-server-rails     
repos to Cocina check: sul-dlss/common-accessioning, sul-dlss/dor_indexing_app, sul-dlss/gis-robot-suite, sul-dlss/google-books, sul-dlss/happy-heron, sul-dlss/hydra_etd, sul-dlss/ksr-app, sul-dlss/modsulator-app-rails, sul-dlss/pre-assembly, sul-dlss/preservation_catalog, sul-dlss/preservation_robots, sul-dlss/robot-console, sul-dlss/sdr-api, sul-dlss/sul_pub, sul-dlss/suri-rails, sul-dlss/technical-metadata-service, sul-dlss/was-registrar-app, sul-dlss/was_robot_suite, sul-dlss/workflow-server-rails
------- COCINA REPORT …
```
> deployer.rb repos_missing_tag: RepoUpdater wants a repo object (not just the string with its name)

- config/settings.yml
Based on suggestions in the slack thread: https://stanfordlib.slack.com/archives/C09M7P91R/p1649684121771599  add some additional comments covering why sul-pub server names are not standardized.
> add comments about sul-pub environments

- config/settings.yml
Because WAS repos are cocina-aware and should be deployed among the cocina repos.
> Add cocina flag to WAS repos

- Gemfile
- Gemfile.lock
- bin/sdr
- config/settings.yml
- lib/deployer.rb
This is no longer held now that we have https://github.com/sul-dlss/puppet/pull/7902 moving forward
Nagios monitors a superset of what we were checking previously, and it can work against boxes behind firewalls.
Ran a deploy against QA
> Prefer Nagios checks over app-specific status checks

- README.md
- bin/sdr
- lib/deployer.rb
This helps us with the default gem conundrum. Usage in this context is documented in the README.
Run against all envs to install the strscan gem.
README
> Optionally run a user-provided command before deploying

- README.md
- dor-services-app is now on ruby 3
- tagging was forgotten by me because it wasn't before deploy section
> README: move up repository tags section

- README.md
- config/settings.yml
- lib/sdr_deploy.rb
Support techmd `retro` environment, which is a non-standard production environment.
> Adds support for non-standard prod environments.

- config/settings.yml
Because gis-robot-suite is now a direct cocina-models consumer, and should be deployed when other cocina-models affected apps are deployed.
> gis-robot-suite IS a direct cocina consumer

- README.md
- bin/sdr
- lib/cocina_checker.rb
- lib/deployer.rb
When deploying, we should be checking the cocina version consistentcy of the released tag.  
We still want to be able to check the default (main) branch.
Fixes #146 
I ran the command with all the different options
README is updated.
> allow cocina-models to be checked for a tag

- lib/cocina_checker.rb
so that the working directory isn't left changed going forward
this got me slightly nicer output in the new mode when i tested:
before:
```
sdr-deploy % bin/sdr check_cocina -t rel-2022-08-01
Updating cached git repository [▣▣▣▣▣▣▣▣▣▣▣▣] (12/12, ETA:  0s) sul-dlss/was_robot_suite   
repos to Cocina check: sul-dlss/argo, sul-dlss/common-accessioning, sul-dlss/dor-services-app, sul-dlss/dor_indexing_app, sul-dlss/gis-robot-suite, sul-dlss/google-books, sul-dlss/happy-heron, sul-dlss/hydra_etd, sul-dlss/pre-assembly, sul-dlss/sdr-api, sul-dlss/was-registrar-app, sul-dlss/was_robot_suite
------- COCINA REPORT -------
for tag rel-2022-08-01 of repos
Found these versions of cocina in use:
0.83.0
/Users/jmartin-sul/software_dev_projects/sdr-deploy/tmp/repos/sul-dlss/argo …
```
> CocinaChecker#switch_repo_to_tag - shell out in a Dir.chdir block 

- README.md
Because I like to be pretty brain dead when doing dep updates and having a relevant exemplar is awesome.
> README: add exemplar for dep update tag

- README.md
It was needed back when we were sorting out our Ubuntu usage on servers but is no longer neeed. It's only noise.
> Remove `bash -lc` jazz from README

- config/settings.yml
We are no longer using this VM to run the website ... it will be a google site for now.
> remove ksr-app from deploy list

- config/settings.yml
we no longer need confirmation like this to deploy argo.
unit tests
settings.yml
> remove confirmation to deploy argo from 10 months ago

- config/settings.yml
See https://github.com/sul-dlss/sul_pub/issues/1618 ... we want to test a branch of sul-pub on UAT and so not want to deploy dependency updates there while we do this.  We will revert then when done with testing.
> temporarily skip sul-pub UAT environment so we can test branch

- config/settings.yml
Reverts sul-dlss/sdr-deploy#220
WoS API branch of sul-pub is now merged and we can deploy everywhere again.
> Revert "temporarily skip sul-pub UAT environment so we can test branch"

- lib/cocina_checker.rb
i am a nitpicky programmer with a lack of self control.
```
% bin/sdr check_cocina
Updating cached git repository [▣▣▣▣▣▣▣▣▣▣▣▣] (12/12, ETA:  0s) sul-dlss/was-registrar-app 
repos to Cocina check: sul-dlss/argo, sul-dlss/common-accessioning, sul-dlss/dor-services-app, sul-dlss/dor_indexing_app, sul-dlss/gis-robot-suite, sul-dlss/google-books, sul-dlss/happy-heron, sul-dlss/hydra_etd, sul-dlss/pre-assembly, sul-dlss/sdr-api, sul-dlss/was-registrar-app, sul-dlss/was_robot_suite
------- COCINA REPORT -------
for default branches of repos
Found these versions of cocina in use:
0.94.0
sul-dlss/argo
sul-dlss/common-accessioning
sul-dlss/google-books
sul-dlss/happy-heron
sul-dlss/hydra_etd
sul-dlss/pre-assembly
sul-dlss/sdr-api
sul-dlss/was-registrar-app
sul-dlss/was_robot_suite
0.94.1 …
```
> CocinaChecker#check_cocina: unique_major_minors becomes a more accurate var name

- README.md
- bin/sdr
- lib/cocina_checker.rb
- lib/deployer.rb
The SDR VMs will soon have MFA turned on for SSH in all environments. We have a solution for weekly mass deploys in place already that uses `sdr-infra` as a jump host, but currently if a developer needs to deploy a single branch for a single repo via capistrano, that requires N * M SSH connections: N being the number of VMs in a given environment and M being the number of steps in the capistrano deployment. Each of these connections will require a separate MFA interaction---which is untenable.
This commit lets us extend our jump host solution to one-off deploys of codebases by allowing `sdr-deploy` to deal with both tags *and* branches.
Did a couple deploys.
> Add ability to deploy & check specified branches in addition to tags

- lib/repo_updater.rb
Because `git clone` used to include the `--depth` argument, the `fetch` git config was set up to *only* fetch `main`, so the git configuration was prohibiting us from being able to verify remote branches. This fixes that.
This work is in support of our push to enable MFA.
Deploys.
> Change how git repositories are cloned to allow remote branches

- Gemfile
- Gemfile.lock
- lib/deployer.rb
Now that we are deploying in a terminal on sdr-infra.stanford.edu the
launching of a browser pointed at nagios doesn't seem to work. I get
prompted for a cookie, and then when I answer "Y" it doesn't seem to
work. This commit prints the URL for clicking on instead.
After:
I ran a `bin/sdr deploy` to stage.
None.
> Remove launchy

- README.md
Add some more info to README on setup for sdr-infra based on my initial efforts.
> add more detail to README

- README.md
I think there is a statement in the README that is now false.   Made it true.
> fix reference to contribsys values

- README.md
Make sure documentation lives in the best place for its audience and purpose.
Blocked by https://github.com/sul-dlss/DeveloperPlaybook/pull/230
> Link to DevPlaybook documentation on SSH configuration

- lib/deployer.rb
- lib/repo_updater.rb
This commit slightly tweaks the progress bar style when deploying and updating repos.
It looks better to me, at least?
> Tweak the progress bar style

- config/settings.yml
No longer needs to be deployed.
> Stop deploying DIA

- .gitignore
- README.md
- config/settings.yml
- lib/deployer.rb
- lib/repo_updater.rb
Allows us to see when a repo has been successfully updated or deployed in a log file.  Useful when the parallel processes fail part without useful output telling you which repo may have caused the problem.
Localhost with an update and a deploy
README updated
> log success output from ssh checking and deploying

- .rubocop.yml
- bin/sdr
- lib/deployer.rb
I have found being able to update the repositories at once to search for code throughout our stack to be helpful. This allows me to refresh the repositories without having to use check_ssh/deploy/etc.
> Add a refresh_repos method and update rubocop

- lib/deployer.rb
So I can quickly verify it's going to the right place
Localhost
> show me where i am deploying for sanity check

- Gemfile.lock
Small housekeeping PR so that this doesn't continue to show up for folks.
> Add newest macos platform to Gemfile.lock

- README.md
- bin/sdr
- config/settings.yml
This should help avoid locking accounts out by verifying that a control master is established before running ssh commands.
Prompts the user to allow a pause for connecting a control master, and a `-c, --control_master` option to skip the prompt.
Uploading Screen Recording 2024-12-17 at 3.59.47 PM.mov…
> Verify control master is open for deploy and check_ssh

- config/settings.yml
We want to tag releases in sul-dlss/speech-to-text but there is nothing to deploy since a Github Action will deploy to AWS.
It hasn't.
> Add speech-to-text

- config/settings.yml
> rialto-orgs does not have a qa environment

- README.md
- bin/sdr
- config/settings.yml
- lib/repo_auditor.rb
Small quality of life addition.
```
running 'bundle audit' for sul-dlss/dlme-airflow
running 'bundle audit' for sul-dlss/common-accessioning
running 'bundle audit' for sul-dlss/dor-services-app
running 'bundle audit' for sul-dlss/argo
running 'bundle audit' for sul-dlss/gis-robot-suite
running 'bundle audit' for sul-dlss/google-books
running 'bundle audit' for sul-dlss/happy-heron
running 'bundle audit' for sul-dlss/hungry-hungry-hippo
running 'bundle audit' for sul-dlss/hydra_etd
running 'bundle audit' for sul-dlss/modsulator-app-rails
running 'bundle audit' for sul-dlss/pre-assembly
running 'bundle audit' for sul-dlss/preservation_catalog
running 'bundle audit' for sul-dlss/preservation_robots
running 'bundle audit' for sul-dlss/rialto-orgs
running 'bundle audit' for …
```
> Add audit_repos in order to run bundle audit against all SDR repos

- README.md
- lib/git_tag_cli.rb
- lib/sdr_cli.rb
Namely: the `sdr` command will always be invoked via `bin/sdr`. Else we can run into conflicts with other `sdr` executables on the path, such as the sdr-client CLI. After making the CLI changes, regenerate the docs so the README faithfully reflects real-life CLI output.
> Convince CLI to emit usage doc that match our expectations

- config/settings.yml
We have an active work cycle where we're replacing hydra_etd (with heracles), and we need to carefully roll that out as we're ready.
> Deploy heracles to etd-qa and -stage and hydra to -prod and -uat
